name: Commit diário automático

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:  

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Git
        run: |
          git config user.name "xavieralves16"
          git config user.email "xavieralves162@gmail.com"

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script de geração
        run: |
          python clipping_gerar.py

      - name: Commit e Push das alterações
        run: |
          git add .
          git commit -m "Atualização automática diária"
          git push
