name: Clipping Diário Automático

on:
  schedule:
    - cron: "0 6 * * *"  # Executa todos os dias às 06:00 UTC (7h em Portugal)
  workflow_dispatch:    # Permite executar manualmente se quiseres

jobs:
  run-clipping:
    runs-on: ubuntu-latest

    steps:
      - name: Obter código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Executar script Clipping
        run: |
          python clipping_gerar.py

      - name: Fazer upload do ficheiro clipping.html como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: clipping_html
          path: clipping.html
